add sys/backup endpoint
bondhome/api-v2 pull request #41
Opened 2021-04-27 22:02 UTC by chrismerck

DRAFT because:
 - need to revise docs to align with implementation

2021-05-28 17:51 UTC, endy-s requested changes
The path change is critical

2021-05-28 17:51 UTC, endy-s commented on common/paths.yaml
> +/v2/sys/snapshot:
Looks like it was implemented as `backup` actually
```suggestion
/v2/sys/backup:
```

2021-05-28 17:51 UTC, endy-s commented on firmware/schemas.yaml
> +        Progress == 1000 iff backup == 2 or restore == 2.
Typo
```suggestion
        Progress == 1000 if backup == 2 or restore == 2.
```

2021-06-01 13:54 UTC, chrismerck commented on firmware/schemas.yaml
> +        Progress == 1000 iff backup == 2 or restore == 2.
Actually, was not a typo. "Iff" stands for "if and only if".

https://en.wikipedia.org/wiki/If_and_only_if

2021-06-30 15:59 UTC, merged