new Features: RGB, RGBW
bondhome/api-v2 pull request #76
Opened 2022-08-26 18:42 UTC by chrismerck

2022-08-29 12:34 UTC, rafaeldantaas requested changes
Looks good to me, I just would call differently setting the color through `hsv` then setting through `rgb`...

2022-08-29 12:34 UTC, rafaeldantaas commented on common/info.yaml
> +      Differnet devices will specify different sets of color presets.
```suggestion
      Different devices will specify different sets of color presets.
```

2022-08-29 12:34 UTC, rafaeldantaas commented on common/info.yaml
> +    - **SetRGB({h:int, s:int, v:int})**
Think we should call `SetColor()` here to avoid conflict with the direct RGB setting action

2022-08-29 15:06 UTC, chrismerck commented on common/info.yaml
> +    - **SetRGB({h:int, s:int, v:int})**
Seems reasonable. Otherwise we would need some logic to make sure that someone doesn't mix variables from RGB-space and HSV-space. But perhaps we should call it `SetHSV()`? Because `SetColor` sounds like it is somehow the preferred way to do it, or would be more flexible. 

---

BTW, is HSV really some preferred space? It seems somehow very intuitive, with the hue wrapping around the center of the cylinder. Interesting to consider how the colorspace would be transformed if humans could see an additional channel of light. Imagine, say, that we could see ultraviolet. Then the first colorspace would change from the RGB cube to the RGBU hyper-cube. What happens to the HSV cylinder? Well we can no longer walk through all the hues with a single degree of freedom. My intuition is that the topology of hue would change from (the circumference of) a circle to the surface of a sphere. We would still have the same concept of saturation---the distance from the center of the sphere. And then that sphere would be traced through the fourth dimension of value (V) similar to how the cylinder is traced. A _hypercylinder_, perhaps?

2022-08-29 16:11 UTC, chrismerck commented
@rafaeldantaas take a look, I renamed a few things to try to clarify.

2022-08-29 19:41 UTC, endy-s approved these changes

2022-08-29 19:41 UTC, endy-s commented on common/info.yaml
> +  Intitively, what is going on is that when producing a pure color,
Did you mean `Intuitively`?
```suggestion
  Intuitively, what is going on is that when producing a pure color, 
```

2022-08-29 19:41 UTC, endy-s commented on common/info.yaml
> +  pure colors are along the top of the tent wall (the top circumferance of
Another typo
```suggestion
  pure colors are along the top of the tent wall (the top circumference of
```

2022-08-29 19:41 UTC, endy-s commented on common/info.yaml
> +      Light is implicitely turned on if off.
Typo?
```suggestion
      Light is implicitly turned on if off.
```

(There are other occurrences)

2022-08-29 19:41 UTC, endy-s commented on common/info.yaml
> +      Implicitly set maximum saturation and then increase Hue by specified
Wrong capitalization?
```suggestion
      Implicitly set maximum saturation and then increase hue by specified
```

2022-08-29 22:07 UTC, chrismerck commented
Something for us to consider is, might we prefer to use arrays rather than objects?

`state = {..., "rgb": [255, 255, 128], "hsv": [120, 1000, 1000], ...}`

versus

`state = {..., "rgb": {"r":255, "g":255, "b":128}, "hsv": {"h":120, "s":1000, "v":1000], ...}`

I'm liking the compactness of the array representation, but the only problem is, how does a client set just one of the channels? 

Maybe SetRGB([128, -1, -1]) if you want to just set the red channel?

@endy-s  @marciogranzotto @natanolibra thoughts on how this effects apps?

2022-08-30 13:48 UTC, chrismerck commented
We decided to stick with the object-in-object.

Updated the docs to reflect implementation.

2022-11-28 14:48 UTC, merged